name: DocHTML -- Build and Deploy

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-docs
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install sphinx==5.0.0 sphinx_rtd_theme # breathe -- not using breathe at the moment
          python3 -m pip install -I docutils==0.16  # Downgrade docutils so that bullet points render properly with Sphinx

      - name: Build Docs
        run: |
          ./docs/builddocs.sh

      - name: Deploy to Webpage
        if: github.event_name == 'push' && github.repository == 'NOAA-GFDL/NDSL' && github.ref == 'refs/tree/xyuan/document'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository-name: xyuan/fms_port
          branch: xyuan/fms_port # The branch the action should deploy to.
          folder: docs/sphinx_doc/_build # The folder the action should deploy.
          commit-message: "Deployed from NOAA-GFDL/NDSL"
